version: '3'
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=production
    deploy:
      mode: replicated
      replicas: 4
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
        failure_action: rollback
  nginx:
    ports:
      - "80:80"
